### ISSUE TITLE
Missing parent post hash in transaction [block #106179/106180 issues]

### ISSUE THREAD

**Issue by donhardman** [deso-protocol/core#227]
The transaction – 3JuETbuXpLNaRSEn4BQGd7f8R3p8gqAo138Bct7euGib7ktuf3nu9a

It has post hash in it – b632a0811a11a432a9966d47a34c15e93bc7dc38969f23b9de673810f8a81eab (that is missing!)

If we check this check, this should never happen – https://github.com/deso-protocol/core/blob/1b9d4d61499d66f3c3f2911496785aa6b95dd5d5/lib/block_view_post.go#L1084-L1104

Reported it in Discord 2 days ago, still no clarification.

I cannot understand how could it happen? Never before we had transactions went to block like this.

And now we have transaction in block that has unexisting parent post hash in it. So the question is will the blockchain sync from scratch? Cuz looks like the issue was caused by disappeared mempool transaction.

Would be great to hear whats wrong and happy if I'm missing somthing but probably not.

**Comment by lazynina** [comment]
@donhardman - the transaction in question has `PostHashToModify` set. In this case, we are updating an existing post instead of creating a new one. When we update an existing post, we DO NOT check if the parent post specified in the txmeta exists, because we do not update the ParentStakeID on the post entry as that would move a post to be a comment on a different post, which isn't a logical operation.

Going to update the discord shortly now - we've resolved the issue with an update to txindex.go. You can see the update here: https://github.com/deso-protocol/core/pull/222/
