### ISSUE TITLE
JWT can't be validated when the user has signed up with metamask

### ISSUE THREAD

**Issue by ItsAditya-xyz** [deso-protocol/core#441]
So, I have been using this code to validate publicKey in backend using JWT: https://gist.github.com/ItsAditya-xyz/a9bbe50a9847d38d1d1d42653ff4a4e9

This has been working fine for all users except when the user has signed up with metamask.

The equivalent code in NodeJS: https://gist.github.com/chafreaky/84be80aa9091b5b015b14d75558d3182 is having the same problem as well.

Likely there is some other way to validate jwt+public key for metamask users?
cc: @AeonSw4n

**Comment by mvanhalen** [comment]
@ItsAditya-xyz check this https://github.com/deso-protocol/deso-workspace/issues/71#issuecomment-1298587342

**Comment by AeonSw4n** [comment]
Good question! JWT for Metamask users works a little differently than JWT for regular DeSo users. The main difference is that the JWT is issued from a derived key, rather than from the main user seed. The JWT payload will tell you which derived key was used to sign the token. If you look at the [JWT-signing function](https://github.com/deso-protocol/identity/blob/43958d4242e489750b675486c6f9d6b55ddefdc5/src/app/signing.service.ts#L20) you can see that we put a JSON `{this.globalVars.claimJwtDerivedPublicKey: derivedPublicKeyBase58Check}` inside the JWT. The key here will evaluate to just `"derivedPublicKeyBase58Check"`.

So what you need to do to validate a JWT for a Metamask user is:
1. Get the JWT payload and look for `"derivedPublicKeyBase58Check"` KV pair.
2. Check whether the user has authorized this derived key
3. Validate JWT off of the derived key.

Lmk if it worked 👍

**Comment by ItsAditya-xyz** [comment]
ugh, that sounds like a lot of work lol

@mvanhalen do you know of any working solution in nodeJS/python?

**Comment by AeonSw4n** [comment]
Can promise you it took more to come up with this lol

**Comment by ItsAditya-xyz** [comment]
Thanks!
Figured out that on using derivedPublicKeyBase58Check, the JWT validation works well with the existing validation code

**Comment by AeonSw4n** [comment]
Glad to hear! Don't forget to hit backend API to verify this derived key is authorized.

**Comment by ItsAditya-xyz** [comment]
yup!
