### ISSUE TITLE
Add support for derived keys

### ISSUE THREAD

**Issue by maebeam** [deso-protocol/core#58]

**Comment by BogdanDidenko** [comment]
Do you read our minds?)
We just discussed it with @iPaulPro today)
Yes, we want to use this for our projects.
but it's not entirely clear how it will look
We have discussed several possible implementations but we are both not experts at encryption, so this is not obvious to us.

It's good if it would develop in open source because:  it will give more developers a chance to adopt these new standards quickly

**Comment by maebeam** [comment]
We did it @AeonSw4n
