### ISSUE TITLE
Historical BitClout prices

### ISSUE THREAD

**Issue by salilsethi** [deso-protocol/core#64]
Currently, there is no way to find historical BitClout prices, especially pre-exchange listing. 

This is important information for several basic metrics (e.g., calculating USD ROI).

Can you please share the function (and BitCoin peg) that can help the dev community identify historical BitClout prices?

I do realize this might not be an "issue" in the strictest sense. However, received guidance to create an issue here for more information on this.

Thank you so much.

**Comment by tijno** [comment]
@salilsethi i never throw anything away

the easiest way to determine the USD price is:

`$0.50 * 2 ^ million bitclout sold`

this always gives you the right answer at the time the pegged USD rate was adjusted.

The `bitclout sold` you can always get from the BITCOIN_EXCHANGE transaction.

However - as I never throw anything away - 

Attached CSV from get-exchange-rate endpoint since 30 March.

[Bitclout Exchange Rate](https://github.com/bitclout/core/files/6802907/Bitclout.-.Sheet10.csv)

**Comment by salilsethi** [comment]
Thank you @tijno :) So to get the historical info, even for historical prices pre-March 30, the onlyy missing piece is the Bitcoin to Bitclout peg, correct?

**Comment by tijno** [comment]
@salilsethi the formula and total nanos sold wild get you close enough in most cases i think.

You could decode the param change / usd exchange rate transactions to get the BTCUSD pegged rate before 30 march.

**Comment by maebeam** [comment]
Closing this since it has been answered 😄
